/**
 * Upstream module paths — committed data (originally extracted from the docs
 * `Source` sections by the now-removed `scripts/unify-demo-layout.ts`, extended
 * to every source by #974). Maps a docs page (pkg/module) to its pin-relative
 * path inside *that page's own* upstream repository, used for the auto-generated
 * `## Source` links on function pages.
 *
 * The repository a path belongs to is never assumed here: it comes from the
 * provenance registry's `source` column (`packages/metadata/src/functions.ts`)
 * through `upstreamSources` below, so the footer label follows the registry
 * instead of being hard-coded. Paths keep each source's own keying — VueUse and
 * react-use resolve to a file, react-hookz / mantine / ahooks to the module
 * directory their pin defines (see `modulePer` in `scripts/update.ts`).
 */
export const upstreamPaths: Record<string, string> = {
  'core/useAsync': 'packages/core/computedAsync/index.ts',
  'core/unrefElement': 'packages/core/unrefElement/index.ts',
  'core/useActiveElement': 'packages/core/useActiveElement/index.ts',
  'core/useAnimate': 'packages/core/useAnimate/index.ts',
  'core/useAsyncQueue': 'packages/core/useAsyncQueue/index.ts',
  'core/useAsyncState': 'packages/core/useAsyncState/index.ts',
  'core/useBase64': 'packages/core/useBase64/index.ts',
  'core/useBattery': 'packages/core/useBattery/index.ts',
  'core/useBluetooth': 'packages/core/useBluetooth/index.ts',
  'core/useBreakpoints': 'packages/core/useBreakpoints/index.ts',
  'core/useBroadcastChannel': 'packages/core/useBroadcastChannel/index.ts',
  'core/useBrowserLocation': 'packages/core/useBrowserLocation/index.ts',
  'core/useCached': 'packages/core/useCached/index.ts',
  'core/useClickOutside': 'packages/core/onClickOutside/index.ts',
  'core/useClipboard': 'packages/core/useClipboard/index.ts',
  'core/useClipboardItems': 'packages/core/useClipboardItems/index.ts',
  'core/useCloned': 'packages/core/useCloned/index.ts',
  'core/useColorMode': 'packages/core/useColorMode/index.ts',
  'core/useConfirmDialog': 'packages/core/useConfirmDialog/index.ts',
  'core/useCountdown': 'packages/core/useCountdown/index.ts',
  'core/useCssSupports': 'packages/core/useCssSupports/index.ts',
  'core/useCssVar': 'packages/core/useCssVar/index.ts',
  'core/useCycleList': 'packages/core/useCycleList/index.ts',
  'core/useDark': 'packages/core/useDark/index.ts',
  'core/useDeviceMotion': 'packages/core/useDeviceMotion/index.ts',
  'core/useDeviceOrientation': 'packages/core/useDeviceOrientation/index.ts',
  'core/useDevicePixelRatio': 'packages/core/useDevicePixelRatio/index.ts',
  'core/useDevicesList': 'packages/core/useDevicesList/index.ts',
  'core/useDisplayMedia': 'packages/core/useDisplayMedia/index.ts',
  'core/useDocumentVisibility': 'packages/core/useDocumentVisibility/index.ts',
  'core/useDraggable': 'packages/core/useDraggable/index.ts',
  'core/useDropZone': 'packages/core/useDropZone/index.ts',
  'core/useElementBounding': 'packages/core/useElementBounding/index.ts',
  'core/useElementByPoint': 'packages/core/useElementByPoint/index.ts',
  'core/useElementHover': 'packages/core/useElementHover/index.ts',
  'core/useElementOverflow': 'packages/core/useElementOverflow/index.ts',
  'core/useElementSize': 'packages/core/useElementSize/index.ts',
  'core/useElementVisibility': 'packages/core/useElementVisibility/index.ts',
  'core/useEventBus': 'packages/core/useEventBus/index.ts',
  'core/useEventListener': 'packages/core/useEventListener/index.ts',
  'core/useEventSource': 'packages/core/useEventSource/index.ts',
  'core/useEyeDropper': 'packages/core/useEyeDropper/index.ts',
  'core/useFavicon': 'packages/core/useFavicon/index.ts',
  'core/useFetch': 'packages/core/useFetch/index.ts',
  'core/useFileDialog': 'packages/core/useFileDialog/index.ts',
  'core/useFileSystemAccess': 'packages/core/useFileSystemAccess/index.ts',
  'core/useFocus': 'packages/core/useFocus/index.ts',
  'core/useFocusWithin': 'packages/core/useFocusWithin/index.ts',
  'core/useFps': 'packages/core/useFps/index.ts',
  'core/useFullscreen': 'packages/core/useFullscreen/index.ts',
  'core/useGamepad': 'packages/core/useGamepad/index.ts',
  'core/useGeolocation': 'packages/core/useGeolocation/index.ts',
  'core/useIdle': 'packages/core/useIdle/index.ts',
  'core/useImage': 'packages/core/useImage/index.ts',
  'core/useInfiniteScroll': 'packages/core/useInfiniteScroll/index.ts',
  'core/useIntersectionObserver': 'packages/core/useIntersectionObserver/index.ts',
  'core/useKeyModifier': 'packages/core/useKeyModifier/index.ts',
  'core/useKeyStroke': 'packages/core/onKeyStroke/index.ts',
  'core/useLiveAnnouncer': 'packages/core/useLiveAnnouncer/index.ts',
  'core/useLocalStorage': 'packages/core/useLocalStorage/index.ts',
  'core/useLongPress': 'packages/core/onLongPress/index.ts',
  'core/useMagicKeys': 'packages/core/useMagicKeys/index.ts',
  'core/useMediaControls': 'packages/core/useMediaControls/index.ts',
  'core/useMediaQuery': 'packages/core/useMediaQuery/index.ts',
  'core/useMemoize': 'packages/core/useMemoize/index.ts',
  'core/useMemory': 'packages/core/useMemory/index.ts',
  'core/useMounted': 'packages/core/useMounted/index.ts',
  'core/useMouse': 'packages/core/useMouse/index.ts',
  'core/useMouseInElement': 'packages/core/useMouseInElement/index.ts',
  'core/useMousePressed': 'packages/core/useMousePressed/index.ts',
  'core/useMutationObserver': 'packages/core/useMutationObserver/index.ts',
  'core/useNavigatorLanguage': 'packages/core/useNavigatorLanguage/index.ts',
  'core/useNetwork': 'packages/core/useNetwork/index.ts',
  'core/useObjectUrl': 'packages/core/useObjectUrl/index.ts',
  'core/useOffsetPagination': 'packages/core/useOffsetPagination/index.ts',
  'core/useOnline': 'packages/core/useOnline/index.ts',
  'core/usePageLeave': 'packages/core/usePageLeave/index.ts',
  'core/useParallax': 'packages/core/useParallax/index.ts',
  'core/useParentElement': 'packages/core/useParentElement/index.ts',
  'core/usePerformanceObserver': 'packages/core/usePerformanceObserver/index.ts',
  'core/usePermission': 'packages/core/usePermission/index.ts',
  'core/usePointer': 'packages/core/usePointer/index.ts',
  'core/usePointerLock': 'packages/core/usePointerLock/index.ts',
  'core/usePointerSwipe': 'packages/core/usePointerSwipe/index.ts',
  'core/usePreferredColorScheme': 'packages/core/usePreferredColorScheme/index.ts',
  'core/usePreferredContrast': 'packages/core/usePreferredContrast/index.ts',
  'core/usePreferredDark': 'packages/core/usePreferredDark/index.ts',
  'core/usePreferredLanguages': 'packages/core/usePreferredLanguages/index.ts',
  'core/usePreferredReducedMotion': 'packages/core/usePreferredReducedMotion/index.ts',
  'core/usePreferredReducedTransparency': 'packages/core/usePreferredReducedTransparency/index.ts',
  'core/usePrevious': 'packages/core/usePrevious/index.ts',
  'core/useRafFn': 'packages/core/useRafFn/index.ts',
  'core/useRefsList': 'packages/core/useTemplateRefsList/index.ts',
  'core/useResizeObserver': 'packages/core/useResizeObserver/index.ts',
  'core/useScreenOrientation': 'packages/core/useScreenOrientation/index.ts',
  'core/useScreenSafeArea': 'packages/core/useScreenSafeArea/index.ts',
  'core/useScriptTag': 'packages/core/useScriptTag/index.ts',
  'core/useScroll': 'packages/core/useScroll/index.ts',
  'core/useScrollLock': 'packages/core/useScrollLock/index.ts',
  'core/useSessionStorage': 'packages/core/useSessionStorage/index.ts',
  'core/useShare': 'packages/core/useShare/index.ts',
  'core/useSorted': 'packages/core/useSorted/index.ts',
  'core/useSpeechRecognition': 'packages/core/useSpeechRecognition/index.ts',
  'core/useSpeechSynthesis': 'packages/core/useSpeechSynthesis/index.ts',
  'core/useStartTyping': 'packages/core/onStartTyping/index.ts',
  'core/useStateDebouncedHistory': 'packages/core/useDebouncedRefHistory/index.ts',
  'core/useStateHistory': 'packages/core/useRefHistory/index.ts',
  'core/useStateManualHistory': 'packages/core/useManualRefHistory/index.ts',
  'core/useStateThrottledHistory': 'packages/core/useThrottledRefHistory/index.ts',
  'core/useStepper': 'packages/core/useStepper/index.ts',
  'core/useStorage': 'packages/core/useStorage/index.ts',
  'core/useStorageAsync': 'packages/core/useStorageAsync/index.ts',
  'core/useStyleTag': 'packages/core/useStyleTag/index.ts',
  'core/useSupported': 'packages/core/useSupported/index.ts',
  'core/useSwipe': 'packages/core/useSwipe/index.ts',
  'core/useTemporalNow': 'packages/core/useTemporalNow/index.ts',
  'core/useTextareaAutosize': 'packages/core/useTextareaAutosize/index.ts',
  'core/useTextDirection': 'packages/core/useTextDirection/index.ts',
  'core/useTextSelection': 'packages/core/useTextSelection/index.ts',
  'core/useTimeAgo': 'packages/core/useTimeAgo/index.ts',
  'core/useTimeAgoIntl': 'packages/core/useTimeAgoIntl/index.ts',
  'core/useTimeoutPoll': 'packages/core/useTimeoutPoll/index.ts',
  'core/useTimestamp': 'packages/core/useTimestamp/index.ts',
  'core/useTitle': 'packages/core/useTitle/index.ts',
  'core/useTransition': 'packages/core/useTransition/index.ts',
  'core/useUrlSearchParams': 'packages/core/useUrlSearchParams/index.ts',
  'core/useUserMedia': 'packages/core/useUserMedia/index.ts',
  'core/useVibrate': 'packages/core/useVibrate/index.ts',
  'core/useVirtualList': 'packages/core/useVirtualList/index.ts',
  'core/useWakeLock': 'packages/core/useWakeLock/index.ts',
  'core/useWebNotification': 'packages/core/useWebNotification/index.ts',
  'core/useWebSocket': 'packages/core/useWebSocket/index.ts',
  'core/useWebWorker': 'packages/core/useWebWorker/index.ts',
  'core/useWebWorkerFn': 'packages/core/useWebWorkerFn/index.ts',
  'core/useWindowFocus': 'packages/core/useWindowFocus/index.ts',
  'core/useWindowScroll': 'packages/core/useWindowScroll/index.ts',
  'core/useWindowSize': 'packages/core/useWindowSize/index.ts',
  'electron/useIpcRenderer': 'packages/electron/useIpcRenderer/index.ts',
  'electron/useIpcRendererInvoke': 'packages/electron/useIpcRendererInvoke/index.ts',
  'electron/useIpcRendererOn': 'packages/electron/useIpcRendererOn/index.ts',
  'electron/useZoomFactor': 'packages/electron/useZoomFactor/index.ts',
  'electron/useZoomLevel': 'packages/electron/useZoomLevel/index.ts',
  'firebase/useRTDB': 'packages/firebase/useRTDB/index.ts',
  'integrations/useAsyncValidator': 'packages/integrations/useAsyncValidator/index.ts',
  'integrations/useAxios': 'packages/integrations/useAxios/index.ts',
  'integrations/useChangeCase': 'packages/integrations/useChangeCase/index.ts',
  'integrations/useCookies': 'packages/integrations/useCookies/index.ts',
  'integrations/useDrauu': 'packages/integrations/useDrauu/index.ts',
  'integrations/useFocusTrap': 'packages/integrations/useFocusTrap/index.ts',
  'integrations/useFuse': 'packages/integrations/useFuse/index.ts',
  'integrations/useIDBKeyval': 'packages/integrations/useIDBKeyval/index.ts',
  'integrations/useJwt': 'packages/integrations/useJwt/index.ts',
  'integrations/useNProgress': 'packages/integrations/useNProgress/index.ts',
  'integrations/useQRCode': 'packages/integrations/useQRCode/index.ts',
  'integrations/useSortable': 'packages/integrations/useSortable/index.ts',
  'math/logicAnd': 'packages/math/logicAnd/index.ts',
  'math/logicNot': 'packages/math/logicNot/index.ts',
  'math/logicOr': 'packages/math/logicOr/index.ts',
  'math/useAbs': 'packages/math/useAbs/index.ts',
  'math/useAverage': 'packages/math/useAverage/index.ts',
  'math/useCeil': 'packages/math/useCeil/index.ts',
  'math/useClamp': 'packages/math/useClamp/index.ts',
  'math/useFloor': 'packages/math/useFloor/index.ts',
  'math/useMath': 'packages/math/useMath/index.ts',
  'math/useMax': 'packages/math/useMax/index.ts',
  'math/useMin': 'packages/math/useMin/index.ts',
  'math/usePrecision': 'packages/math/usePrecision/index.ts',
  'math/useProjection': 'packages/math/useProjection/index.ts',
  'math/useRound': 'packages/math/useRound/index.ts',
  'math/useSum': 'packages/math/useSum/index.ts',
  'math/useTrunc': 'packages/math/useTrunc/index.ts',
  'rxjs/useWatchExtractedObservable': 'packages/rxjs/watchExtractedObservable/index.ts',
  'shared/createEventHook': 'packages/shared/createEventHook/index.ts',
  'shared/createGlobalState': 'src/factory/createGlobalState.ts',
  'shared/isDefined': 'packages/shared/isDefined/index.ts',
  'shared/syncState': 'packages/shared/syncRef/index.ts',
  'shared/syncStates': 'packages/shared/syncRefs/index.ts',
  'shared/until': 'packages/shared/until/index.ts',
  'shared/useArrayDifference': 'packages/shared/useArrayDifference/index.ts',
  'shared/useArrayEvery': 'packages/shared/useArrayEvery/index.ts',
  'shared/useArrayFilter': 'packages/shared/useArrayFilter/index.ts',
  'shared/useArrayFind': 'packages/shared/useArrayFind/index.ts',
  'shared/useArrayFindIndex': 'packages/shared/useArrayFindIndex/index.ts',
  'shared/useArrayFindLast': 'packages/shared/useArrayFindLast/index.ts',
  'shared/useArrayIncludes': 'packages/shared/useArrayIncludes/index.ts',
  'shared/useArrayJoin': 'packages/shared/useArrayJoin/index.ts',
  'shared/useArrayMap': 'packages/shared/useArrayMap/index.ts',
  'shared/useArrayReduce': 'packages/shared/useArrayReduce/index.ts',
  'shared/useDateFormat': 'packages/shared/useDateFormat/index.ts',
  'shared/useInterval': 'packages/shared/useInterval/index.ts',
  'shared/useIntervalFn': 'packages/shared/useIntervalFn/index.ts',
  'shared/useLastChanged': 'packages/shared/useLastChanged/index.ts',
  'shared/useStateAutoReset': 'packages/shared/refAutoReset/index.ts',
  'shared/useStateDefault': 'packages/shared/refDefault/index.ts',
  'shared/useStateManualReset': 'packages/shared/refManualReset/index.ts',
  'shared/useStateThrottled': 'packages/shared/refThrottled/index.ts',
  'shared/useStateWithControl': 'packages/shared/refWithControl/index.ts',
  'shared/useThrottleFn': 'packages/shared/useThrottleFn/index.ts',
  'shared/useTimeout': 'packages/shared/useTimeout/index.ts',
  'shared/useTimeoutFn': 'packages/shared/useTimeoutFn/index.ts',
  'shared/useToNumber': 'packages/shared/useToNumber/index.ts',
  'shared/useWatchArray': 'packages/shared/watchArray/index.ts',
  'shared/useWatchAtMost': 'packages/shared/watchAtMost/index.ts',
  'shared/useWatchDebounced': 'packages/shared/watchDebounced/index.ts',
  'shared/useWatchDeep': 'packages/shared/watchDeep/index.ts',
  'shared/useWatchIgnorable': 'packages/shared/watchIgnorable/index.ts',
  'shared/useWatchImmediate': 'packages/shared/watchImmediate/index.ts',
  'shared/useWatchOnce': 'packages/shared/watchOnce/index.ts',
  'shared/useWatchPausable': 'packages/shared/watchPausable/index.ts',
  'shared/useWatchThrottled': 'packages/shared/watchThrottled/index.ts',
  'shared/useWatchTriggerable': 'packages/shared/watchTriggerable/index.ts',
  'shared/useWatchWithFilter': 'packages/shared/watchWithFilter/index.ts',
  'shared/useWhenever': 'packages/shared/whenever/index.ts',
  'shared/utils': 'packages/shared/utils/index.test.ts',
  // --- Non-VueUse sources (#974) -------------------------------------------
  // The list above is VueUse-only, so a react-use / react-hookz / mantine /
  // ahooks page emitted no upstream link at all. These are the
  // resolver's own paths (`meta/functions.md`), each verified against the pinned
  // checkout; the source of a page — and so its footer label and repository —
  // comes from the registry, never from this map.
  // react-use (17)
  'core/useAsyncFn': 'src/useAsyncFn.ts',
  'shared/createMemo': 'src/factory/createMemo.ts',
  'shared/createReducer': 'src/factory/createReducer.ts',
  'shared/useDeepCompareEffect': 'src/useDeepCompareEffect.ts',
  'shared/useEffectOnce': 'src/useEffectOnce.ts',
  'shared/useError': 'src/useError.ts',
  'shared/useIsomorphicLayoutEffect': 'src/useIsomorphicLayoutEffect.ts',
  'shared/useLatest': 'src/useLatest.ts',
  'shared/useList': 'src/useList.ts',
  'shared/useLogger': 'src/useLogger.ts',
  'shared/useMethods': 'src/useMethods.ts',
  'shared/useMount': 'src/useMount.ts',
  'shared/useRafState': 'src/useRafState.ts',
  'shared/useShallowCompareEffect': 'src/useShallowCompareEffect.ts',
  'shared/useUnmount': 'src/useUnmount.ts',
  'shared/useUpdate': 'src/useUpdate.ts',
  'shared/useUpdateEffect': 'src/useUpdateEffect.ts',
  // react-hookz (2): `src/<name>/index.ts` modules.
  'shared/useMap': 'src/useMap',
  'shared/useSet': 'src/useSet',
  // mantine (7): kebab-cased directories (or the package barrel, for `useId`).
  'core/useCollapse': 'packages/@mantine/hooks/src/use-collapse',
  'core/useFocusReturn': 'packages/@mantine/hooks/src/use-focus-return',
  'core/useHotkeys': 'packages/@mantine/hooks/src/use-hotkeys',
  'core/useId': 'packages/@mantine/hooks/src',
  'core/useMask': 'packages/@mantine/hooks/src/use-mask',
  'core/useSplitter': 'packages/@mantine/hooks/src/use-splitter',
  'shared/useIsFirstRender': 'packages/@mantine/hooks/src/use-is-first-render',
  // ahooks (7): `packages/hooks/src/<name>` modules.
  'core/useClickAway': 'packages/hooks/src/useClickAway',
  'core/useKeyPress': 'packages/hooks/src/useKeyPress',
  'shared/useIntervalRafFn': 'packages/hooks/src/useRafInterval',
  'shared/useSafeState': 'packages/hooks/src/useSafeState',
  'shared/useTimeoutRafFn': 'packages/hooks/src/useRafTimeout',
  'shared/useTrackedEffect': 'packages/hooks/src/useTrackedEffect',
  'shared/useUnmountedRef': 'packages/hooks/src/useUnmountedRef',
}

/** One upstream source, as the `## Source` footer renders it. */
export interface UpstreamSource {
  /** Footer link label. */
  label: string
  /** Repository root the pinned checkout comes from. */
  repo: string
  /**
   * Branch of the pinned checkout. Absent for a source with no pinned module
   * path to link, whose link then stops at the repository root rather than
   * inventing a path that cannot be verified.
   */
  branch?: string
}

/**
 * The upstream repositories reause ports from, keyed by the source id the
 * provenance registry records (`scripts/update.ts`'s `SOURCES`). A source that
 * is not listed here gets no footer link. The map also carries an upstream
 * reause only ever links to — ported from nothing, re-exported by nothing.
 */
export const upstreamSources: Record<string, UpstreamSource> = {
  'vueuse': { label: 'VueUse', repo: 'https://github.com/vueuse/vueuse', branch: 'main' },
  'react-use': { label: 'react-use', repo: 'https://github.com/streamich/react-use', branch: 'master' },
  'react-hookz': { label: 'react-hookz', repo: 'https://github.com/react-hookz/web', branch: 'master' },
  'mantine': { label: 'Mantine', repo: 'https://github.com/mantinedev/mantine', branch: 'master' },
  'ahooks': { label: 'ahooks', repo: 'https://github.com/alibaba/hooks', branch: 'master' },
  // External link only: reause neither ports nor re-exports `@react-spring/web`,
  // so the entry carries the repository a link should point at and no branch.
  'react-spring': { label: 'react-spring', repo: 'https://github.com/pmndrs/react-spring' },
}
