import { existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { getExportsSize } from 'export-size'
import { packages } from '../meta/packages'
import { readJSON, root } from './utils'

const MD = 'packages/export-size.md'
const JSON_FILE = 'packages/export-size.json'
const SCRIPT_URL = 'https://github.com/hairyf/reause/blob/main/scripts/export-size.ts'

/**
 * React is never counted: every entry imports it and it is a peer dependency the
 * consumer already ships. `react/jsx-runtime` has to be listed *explicitly* —
 * left to itself rollup resolves React's CJS file and dies with `'jsx' is not
 * exported by …/jsx-runtime.js`, the interop error this script used to treat as
 * a dead end (see `.github/workflows/export-size.yml`).
 */
const REACT_EXTERNAL = [
  'react',
  'react-dom',
  'react/jsx-runtime',
  'react/jsx-dev-runtime',
  'react-dom/client',
]

/** `248 B` / `1.35 kB` — the spelling the docs page's Export Size row shows. */
function formatSize(bytes: number): string {
  if (bytes < 1000)
    return `${bytes} B`
  return `${(bytes / 1000).toFixed(2)} kB`
}

/** Markdown table in the shape `eslint --fix` (prettier) keeps: padded, left-aligned. */
function markdownTable(rows: string[][]): string {
  const widths = rows[0].map((_, column) => Math.max(...rows.map(row => row[column].length)))
  function line(cells: string[]): string {
    return `| ${cells.map((cell, column) => cell.padEnd(widths[column])).join(' | ')} |`
  }
  return [
    line(rows[0]),
    `| ${widths.map(width => '-'.repeat(width)).join(' | ')} |`,
    ...rows.slice(1).map(line),
  ].join('\n')
}

/**
 * Measure every export of every built package and write both
 * `packages/export-size.md` and `packages/export-size.json`.
 *
 * Mirrors VueUse's `scripts/export-size.ts`: each figure is the min+gzipped size
 * of **one individual API** bundled on its own (`export-size` + rollup, React
 * external), not the size of a built entry file. The json is the source of the
 * docs page's `Export Size` row (`FunctionInfo.vue`), keyed by exported name the
 * way upstream's `export-size.json` is.
 *
 * Requires `npm run build` to have run first.
 */
export async function exportSize() {
  const { version } = readJSON('package.json') as { version: string }
  const measured = packages.filter(pkg => pkg.name !== 'metadata' && pkg.build !== false)

  // Never emit a partial page: a package without dist means the build is missing.
  const missing = measured.filter(pkg => !existsSync(join(root, `packages/${pkg.name}/dist/index.js`)))
  if (missing.length > 0) {
    console.warn('[size] no dist output found — run `npm run build` first')
    console.warn(`[size] missing: ${missing.map(pkg => pkg.display).join(', ')}`)
    return
  }

  const md: string[] = [
    '# Export size\n',
    `version: ${version}<br>`,
    `measured: ${new Date().toISOString().slice(0, 10)}<br>`,
    `generated by [\`npm run size\`](${SCRIPT_URL}) (run \`npm run build\` first)\n`,
    '> Each figure is the **min+gzipped size of one individual API** — that export bundled on its own, with `react` external. Since the exports share utilities underneath, importing two functions does NOT sum their entries (the real result is usually smaller, and it depends on your bundler and minifier) — treat this list as a reference only.\n',
  ]
  const sizes: Record<string, string> = {}

  for (const pkg of measured) {
    const { exports } = await getExportsSize({
      pkg: `./packages/${pkg.name}`,
      output: false,
      bundler: 'rollup',
      external: [...REACT_EXTERNAL, ...(pkg.external || [])],
      // `@reause/shared` is counted inside each consumer's figure (upstream
      // includes `@vueuse/shared` the same way); every other workspace package
      // stays external, so importing core + integrations does not double-count.
      includes: pkg.name === 'shared' ? undefined : ['@reause/shared'],
    })

    // Largest first, name as the tie-break so repeated runs are byte-identical.
    const entries = [...exports].sort((a, b) => b.minzipped - a.minzipped || a.name.localeCompare(b.name))
    for (const entry of entries)
      sizes[entry.name] = formatSize(entry.minzipped)

    md.push(`<kbd>${pkg.display}</kbd>\n`)
    md.push(markdownTable([
      ['Function', 'min+gzipped'],
      ...entries.map(entry => [`\`${entry.name}\``, formatSize(entry.minzipped)]),
    ]))
    md.push('')
    console.log(`[size] ${pkg.display} — ${entries.length} exports`)
  }

  writeFileSync(join(root, MD), `${md.join('\n').replace(/\r\n/g, '\n').trimEnd()}\n`, 'utf-8')
  writeFileSync(join(root, JSON_FILE), `${JSON.stringify(sizes, null, 2)}\n`, 'utf-8')
  console.log(`[size] wrote ${MD} and ${JSON_FILE} (${Object.keys(sizes).length} exports)`)
}

if (process.argv[1]?.endsWith('export-size.ts'))
  exportSize()
